name: Update Port with YouTube Playlist Data

on:
  workflow_dispatch:
    inputs:
      playlistid:
        description: 'ID of the YouTube playlist'
        required: true
      port_context:
        description: 'Port context payload'
        required: true

jobs:
  update_port:
    runs-on: ubuntu-latest
    env:
      PORT_CLIENT_ID: ${{ secrets.PORT_CLIENT_ID }}
      PORT_CLIENT_SECRET: ${{ secrets.PORT_CLIENT_SECRET }}
      PORT_RUN_ID: ${{ fromJson(inputs.port_context).runId }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Create Python script
        run: |
          cat << 'EOF' > fetch_youtube.py
          # ... (keep your existing Python script here)
          EOF

      - name: Fetch and Modify YouTube Playlist Data
        id: fetch_modify_data
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          PLAYLIST_ID: ${{ inputs.playlistid }}
        run: python fetch_youtube.py

      - name: Create Playlist in Port
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: UPSERT
          identifier: ${{ steps.fetch_modify_data.outputs.playlist_playlistId }}
          blueprint: playlist
          properties: |-
            {
              "playlistId": "${{ steps.fetch_modify_data.outputs.playlist_playlistId }}",
              "title": "${{ steps.fetch_modify_data.outputs.playlist_title }}",
              "description": "${{ steps.fetch_modify_data.outputs.playlist_description }}",
              "thumbnailUrl": "${{ steps.fetch_modify_data.outputs.playlist_thumbnailUrl }}",
              "videoCount": "${{ steps.fetch_modify_data.outputs.playlist_videoCount }}",
              "created_at": "${{ steps.fetch_modify_data.outputs.playlist_created_at }}"
            }

      - name: Upsert Video Data into Port
        if: steps.fetch_modify_data.outputs.video_count > 0
        run: |
          for i in $(seq 0 $((steps.fetch_modify_data.outputs.video_count - 1)));
          do
            echo "Upserting video $i"
            VIDEO_ID=$(cat $GITHUB_OUTPUT | grep -E "^videoId_$i=" | cut -d'=' -f2)
            TITLE=$(cat $GITHUB_OUTPUT | grep -E "^title_$i=" | cut -d'=' -f2)
            DESCRIPTION=$(cat $GITHUB_OUTPUT | grep -E "^description_$i=" | cut -d'=' -f2)
            THUMBNAIL_URL=$(cat $GITHUB_OUTPUT | grep -E "^thumbnailUrl_$i=" | cut -d'=' -f2)
            DURATION=$(cat $GITHUB_OUTPUT | grep -E "^duration_$i=" | cut -d'=' -f2)
            VIEW_COUNT=$(cat $GITHUB_OUTPUT | grep -E "^viewCount_$i=" | cut -d'=' -f2)
            LIKE_COUNT=$(cat $GITHUB_OUTPUT | grep -E "^likeCount_$i=" | cut -d'=' -f2)
            COMMENT_COUNT=$(cat $GITHUB_OUTPUT | grep -E "^commentCount_$i=" | cut -d'=' -f2)

            curl -X POST -H "Content-Type: application/json" -d '{
              "clientId": "${{ secrets.PORT_CLIENT_ID }}",
              "clientSecret": "${{ secrets.PORT_CLIENT_SECRET }}",
              "baseUrl": "https://api.getport.io",
              "operation": "UPSERT",
              "identifier": "'"$VIDEO_ID"'",
              "blueprint": "video",
              "properties": {
                "videoId": "'"$VIDEO_ID"'",
                "title": "'"$TITLE"'",
                "description": "'"$DESCRIPTION"'",
                "thumbnailUrl": "'"$THUMBNAIL_URL"'",
                "duration": "'"$DURATION"'",
                "viewCount": '"$VIEW_COUNT"',
                "likeCount": '"$LIKE_COUNT"',
                "commentCount": '"$COMMENT_COUNT"'
              },
              "relations": {
                "belongs_to_playlist": "${{ steps.fetch_modify_data.outputs.playlist_playlistId }}"
              }
            }' ${{ env.PORT_BASE_URL }}/api/upsert
          done
        env:
          PORT_BASE_URL: https://api.getport.io
