name: Update Port with Modified Name
on:
  workflow_dispatch:
    inputs:
      firstname:
        type: string
jobs:
  update_port:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Modify Inputs with Python
        id: modify_inputs
        run: |
          name = "${{ github.event.inputs.firstname }}-updated"
          echo "::set-output name=modified_firstname::${name}"
      - name: Update Port using GitHub API
        env:
          CLIENT_ID: tbmXaNhpgpYiZpYe5HqRYR9ZWSe0tJGV
          CLIENT_SECRET: lZrhNU5u7W8plwejnnDshOuuIOlU6IN4rLBBzDIfnzarsdljw7X88lKgdlT5BsG9
        run: |
          import requests
          import json

          url = "https://api.getport.io/v1/port/newoneautomation"
          payload = {
              "name": "${{ steps.modify_inputs.outputs.modified_firstname }}",
              "blueprint": "newone",
              "team": ["myTeam"],
              "icon": "GithubActions"
          }
          headers = {
              'Content-Type': 'application/json',
              'Authorization': f'Bearer {CLIENT_ID}:{CLIENT_SECRET}'
          }
          response = requests.request("PUT", url, headers=headers, data=json.dumps(payload))
          print(response.text.encode('utf8'))
