name: Update Port with Modified Name and Age

on:
  workflow_dispatch:
    inputs:
      firstname:
        type: string

jobs:
  update_port:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Modify Inputs with Python
        id: modify_inputs
        run: |
          name = "${{ github.event.inputs.firstname }}-updated"
          echo "::set-output firstname=modified_firstname::${firstname}"

      - name: Update Port
        uses: port-labs/port-github-action@v1
        with:
          clientId: tbmXaNhpgpYiZpYe5HqRYR9ZWSe0tJGV
          clientSecret: lZrhNU5u7W8plwejnnDshOuuIOlU6IN4rLBBzDIfnzarsdljw7X88lKgdlT5BsG9
          baseUrl: https://api.getport.io
          operation: UPSERT
          identifier: newoneautomation
          icon: GithubActions
          blueprint: newone
          team: "['myTeam']"
          properties: |-
            {
              "name": "${{ steps.modify_inputs.outputs.modified_firstname }}"
            }
