name: Update Port with YouTube Playlist Data
on:
  workflow_dispatch:
    inputs:
      playlistid:
        description: 'ID of the YouTube playlist'
        required: true
      port_context:
        description: 'Port context payload'
        required: true

jobs:
  update_port:
    runs-on: ubuntu-latest
    env:
      PORT_CLIENT_ID: ${{ secrets.PORT_CLIENT_ID }}
      PORT_CLIENT_SECRET: ${{ secrets.PORT_CLIENT_SECRET }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PORT_RUN_ID: ${{ fromJson(inputs.port_context).runId }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Create Python script
        run: |
          cat << 'EOF' > fetch_youtube.py
          import os
          import requests
          import json
          from datetime import datetime

          # Constants and setup
          YOUTUBE_API_KEY = os.environ['YOUTUBE_API_KEY']
          print('YOUTUBE_API_KEY:', '***' if YOUTUBE_API_KEY else 'Missing')
          playlist_id = os.environ['PLAYLIST_ID']
          print('PLAYLIST_ID:', playlist_id)
          PORT_CLIENT_ID = os.environ['PORT_CLIENT_ID']
          print('PORT_CLIENT_ID:', repr(PORT_CLIENT_ID))
          PORT_CLIENT_SECRET = os.environ['PORT_CLIENT_SECRET']
          print('PORT_CLIENT_SECRET:', repr(PORT_CLIENT_SECRET))
          API_URL = 'https://api.getport.io/v1'

          credentials = {
              'clientId': PORT_CLIENT_ID.strip(),
              'clientSecret': PORT_CLIENT_SECRET.strip()
          }

          print("Credentials payload:", json.dumps(credentials))

          def fetch_playlist_details(playlist_id):
              url = f'https://www.googleapis.com/youtube/v3/playlists?part=snippet,contentDetails,status&id={playlist_id}&key={YOUTUBE_API_KEY}'
              response = requests.get(url)
              print("Playlist details response status:", response.status_code)
              print("Playlist details response content:", response.content)
              response.raise_for_status()
              return response.json()['items'][0]

          def fetch_video_details(video_id):
              url = f'https://www.googleapis.com/youtube/v3/videos?part=snippet,contentDetails,statistics&id={video_id}&key={YOUTUBE_API_KEY}'
              response = requests.get(url)
              print(f"Video {video_id} details response status:", response.status_code)
              response.raise_for_status()
              return response.json()['items'][0]

          # Get Port access token
          token_response = requests.post(f'{API_URL}/auth/access_token', json=credentials)
          print("Token request response status:", token_response.status_code)
          print("Token request response content:", token_response.content)

          if token_response.status_code != 200:
              print("Failed to obtain access token. Check client credentials and endpoint.")
          else:
              access_token = token_response.json().get('accessToken')
              print(f'Access token: {"Obtained" if access_token else "None"}')

          headers = {
              'Authorization': f'Bearer {access_token}' if access_token else 'Bearer <missing>'
          }

          # Check if access token retrieval was successful
          if not access_token:
              print("Exiting script due to missing access token.")
              exit(1)

          # Fetch playlist details
          try:
              playlist = fetch_playlist_details(playlist_id)
          except Exception as e:
              print(f"Error fetching playlist details: {e}")
              exit(1)

          # Create playlist in Port
          playlist_entity = {
              'identifier': playlist['id'],
              'title': playlist['snippet']['title'],
              'properties': {
                  'playlistId': playlist['id'],
                  'title': playlist['snippet']['title'],
                  'description': playlist['snippet']['description'],
                  'thumbnailUrl': playlist['snippet']['thumbnails']['default']['url'],
                  'videoCount': playlist['contentDetails']['itemCount'],
                  'created_at': playlist['snippet']['publishedAt']
              }
          }

          playlist_response = requests.post(f'{API_URL}/blueprints/playlist/entities?upsert=true', json=playlist_entity, headers=headers)
          print(f"Playlist sync status: {playlist_response.status_code}")
          print("Playlist sync response content:", playlist_response.content)

          # Fetch and upload videos
          try:
              videos = fetch_playlist_videos(playlist_id)
          except Exception as e:
              print(f"Error fetching playlist videos: {e}")
              exit(1)

          for video in videos:
              snippet = video['snippet']
              statistics = video.get('statistics', {})
              content_details = video.get('contentDetails', {})
              
              video_entity = {
                  'identifier': video['id'],
                  'title': snippet['title'],
                  'properties': {
                      'videoId': video['id'],
                      'title': snippet['title'],
                      'description': snippet['description'],
                      'thumbnailUrl': snippet['thumbnails']['default']['url'],
                      'duration': content_details.get('duration', ''),
                      'viewCount': int(statistics.get('viewCount', 0)),
                      'likeCount': int(statistics.get('likeCount', 0)),
                      'commentCount': int(statistics.get('commentCount', 0))
                  },
                  'relations': {
                      'belongs_to_playlist': playlist['id']
                  }
              }
              
              video_response = requests.post(f'{API_URL}/blueprints/video/entities?upsert=true', json=video_entity, headers=headers)
              print(f"Video {video['id']} sync status: {video_response.status_code}")
              print("Video sync response content:", video_response.content)
          EOF

      - name: Fetch and Process YouTube Data
        id: fetch_data
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          PLAYLIST_ID: ${{ inputs.playlistid }}
          PORT_CLIENT_ID: ${{ secrets.PORT_CLIENT_ID }}
          PORT_CLIENT_SECRET: ${{ secrets.PORT_CLIENT_SECRET }}
        run: python fetch_youtube.py
