name: Update Port with YouTube Playlist Data
on:
  workflow_dispatch:
    inputs:
      playlistid:
        description: 'ID of the YouTube playlist'
        required: true
      port_context:
        description: 'Port context payload'
        required: true

jobs:
  # Job to obtain the Port access token
  obtain_token:
    runs-on: ubuntu-latest
    env:
      PORT_CLIENT_ID: ${{ secrets.PORT_CLIENT_ID }}
      PORT_CLIENT_SECRET: ${{ secrets.PORT_CLIENT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jq for JSON processing
        run: sudo apt-get install -y jq

      - name: Get Port access token
        id: get_token
        run: |
          set -e
          PORT_CLIENT_ID=$(echo "$PORT_CLIENT_ID" | xargs)
          PORT_CLIENT_SECRET=$(echo "$PORT_CLIENT_SECRET" | xargs)
          
          get_port_access_token() {
            response=$(curl -s -X POST "https://api.getport.io/v1/auth/access_token" \
              -H "Content-Type: application/json" \
              -d '{
                "clientId": "'"$PORT_CLIENT_ID"'",
                "clientSecret": "'"$PORT_CLIENT_SECRET"'"
              }')
            
            if echo "$response" | grep -q '"ok":false'; then
              echo "Error obtaining access token: $(echo "$response" | jq -r '.error' )"
              exit 1
            fi

            access_token=$(echo "$response" | jq -r '.accessToken // empty')
            if [ -z "$access_token" ]; then
              echo "Failed to retrieve access token. Response: $response"
              exit 1
            fi

            echo "$access_token"
          }

          ACCESS_TOKEN=$(get_port_access_token)
          echo "Access token obtained: ${ACCESS_TOKEN:0:50}..."
          echo "::set-output name=access_token::$ACCESS_TOKEN"

  # Job to process the playlist
  process_playlist:
    runs-on: ubuntu-latest
    needs: obtain_token
    env:
      ACCESS_TOKEN: ${{ needs.obtain_token.outputs.access_token }}
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      PLAYLIST_ID: ${{ inputs.playlistid }}

    steps:
      - name: Install jq for JSON processing
        run: sudo apt-get install -y jq

      - name: Fetch playlist details and report to Port
        id: fetch_playlist
        run: |
          set -e
          playlist_response=$(curl -s "https://www.googleapis.com/youtube/v3/playlists?part=snippet,contentDetails,status&id=${PLAYLIST_ID}&key=${YOUTUBE_API_KEY}")
          playlist_id=$(echo $playlist_response | jq -r '.items[0].id')
          playlist_title=$(echo $playlist_response | jq -r '.items[0].snippet.title')
          playlist_description=$(echo $playlist_response | jq -r '.items[0].snippet.description')
          playlist_thumbnail=$(echo $playlist_response | jq -r '.items[0].snippet.thumbnails.default.url')
          playlist_video_count=$(echo $playlist_response | jq -r '.items[0].contentDetails.itemCount')
          playlist_published_at=$(echo $playlist_response | jq -r '.items[0].snippet.publishedAt')

          playlist_entity=$(jq -n --arg id "$playlist_id" --arg title "$playlist_title" \
            --arg description "$playlist_description" --arg thumbnailUrl "$playlist_thumbnail" \
            --arg videoCount "$playlist_video_count" --arg created_at "$playlist_published_at" \
            '{
              identifier: $id,
              title: $title,
              properties: {
                playlistId: $id,
                title: $title,
                description: $description,
                thumbnailUrl: $thumbnailUrl,
                videoCount: ($videoCount | tonumber),
                created_at: $created_at
              }
            }')

          echo "Payload: $playlist_entity"
          response=$(curl --http1.1 -s -w "%{http_code}\n" -o /tmp/playlist_response.json -X POST "https://api.getport.io/v1/blueprints/playlist/entities?upsert=true" \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$playlist_entity")

          http_code=$(cat /tmp/playlist_response.json | tail -n 1)
          body=$(cat /tmp/playlist_response.json)

          if [[ "$http_code" != "2" ]]; then
            echo "Failed to push playlist to Port. HTTP code: $http_code"
            echo "Response Body: $body"
            exit 1
          fi

  # Job to process videos in the playlist
  process_videos:
    runs-on: ubuntu-latest
    needs: process_playlist
    env:
      ACCESS_TOKEN: ${{ needs.obtain_token.outputs.access_token }}
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      PLAYLIST_ID: ${{ inputs.playlistid }}

    steps:
      - name: Install jq for JSON processing
        run: sudo apt-get install -y jq

      - name: Fetch and process videos
        run: |
          set -e
          next_page_token=""
          while :; do
            url="https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&maxResults=50&playlistId=${PLAYLIST_ID}&key=${YOUTUBE_API_KEY}${next_page_token:+&pageToken=$next_page_token}"
            response=$(curl -s "$url")
            next_page_token=$(echo $response | jq -r '.nextPageToken // empty')

            video_ids=$(echo $response | jq -r '.items[].snippet.resourceId.videoId')
            for video_id in $video_ids; do
              video_details=$(curl -s "https://www.googleapis.com/youtube/v3/videos?part=snippet,contentDetails,statistics&id=$video_id&key=${YOUTUBE_API_KEY}")
              video_title=$(echo $video_details | jq -r '.items[0].snippet.title
